### ISSUE TITLE
Cookies issue

### ISSUE THREAD

**Issue by Crumblegdl** [r0oth3x49/lynda-dl#52] opened 2018-11-29 10:37 UTC
Hi There,

I am using latest version of master branch.

I have tried over and over to get cookies working.

I have tried exporting my cookies using cookies.txt and also the copy request headers method.

I navigate to lynda and login using organization portal. I go to a video and click play. I check my network tab in inspect element and filter by xhr.

I copy one using right click > copy request header

I paste into a text file.

I run lynda-dl using 

```
python lynda-dl.py --cookies cookies.txt https://www.lynda.com/Substance-Painter-tutorials/Substance-Painter-2018-Essential-Training/746259-2.html
```

I get cookies error please provide a request header [seen here](https://i.imgur.com/s1w3eJO.png).

i have tried using nearly all the links that show up in my network tab, so i am unsure if something has changed.

What would be great if it could just use the cookies.txt plugin aswell.

I also tried using the -organisation portal and had no luck with it. It says  "Failed to extract csrftoken."

Any help would be great thanks!

**Comment by Crumblegdl** [comment] 2018-11-29 10:56
After logging out and back into lynda and tracking my network requests, I was able to find one that let me login. however it immediately tells me 

JSONDecodeError: it seems your cookies got expired, provide again.

Then of course following that network request down the line, and copying every single one that has a cookie in it yields the same results as before. 

So it is my understanding they may have changed something with how their request headers work?

**Comment by r0oth3x49** [comment] 2018-11-29 11:35
@Crumblegdl i cannot reproduce the error you are facing you might be mistaking at some point. can you please share your credentials and details (course url etc) on my [email](mailto:nasir251292@gmail.com) so that i can reproduce & fix ASAP.

BTW.
for me cookie based and simple organization login both working fine.

**Comment by Crumblegdl** [comment] 2018-11-29 11:51
i'm not sure where i can be mistaken, I followed your instructions and wrote them out here.

Is there anywhere in those steps i wrote where I am wrong?

using a cookie should just work if i am logged in, and I am. 
sending email now.

**Comment by r0oth3x49** [comment] 2018-11-29 18:50
@Crumblegdl as you said in a email, you found another way so i 'm closing this issue

**Closed as completed by r0oth3x49** 2018-11-29 18:50 UTC

**Comment by PalmCivetMenace** [comment] 2018-12-06 18:20
I have the same problem as well here ...

**Comment by Crumblegdl** [comment] 2018-12-06 23:10
> 
> 
> I have the same problem as well here ...

Check out Lynda-Decryptor, just use the desktop app to download the courses you want and then you can decrypt them to mp4 in seconds.

**Comment by HeIp** [comment] 2018-12-07 14:41
<img width="537" alt="image" src="https://user-images.githubusercontent.com/31706214/49653893-4210a380-fa04-11e8-8b77-1e4a5cee41c6.png">
same issue , same as everything @Crumblegdl  mentioned in original issue "Failed to extract csrftoken." , Unfortunately on Mac OS

**Comment by AntiGov** [comment] 2018-12-19 01:17
JSONDecodeError : it seems your cookies got expired, provide again.

**Comment by HeIp** [comment] 2018-12-19 04:39
@r0oth3x49  Should re-open this issue.
